language: csharp
solution: Source/MvcFinalProject.sln
install:
  - nuget restore Source/MvcFinalProject.sln
# script:
  # - xbuild /p:Configuration=Debug Source/MvcFinalProject.sln
  # - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyPoject.Tests/bin/Release/MyProject.Tests.dll
notifications:
  email: false