version: 1.0.{build}
os: Visual Studio 2015
init:
- git config --global core.autocrlf true
install:
# - cmd: pip install codecov
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore Source/JustOrderIt.sln
build:
  project: Source/JustOrderIt.sln
  verbosity: Normal
test_script:
  - .\Source\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -output:.\JustOrderIt_coverage.xml -target:"Source\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"Source\Tests\JustOrderIt.Services.Web.Tests\bin\Debug\JustOrderIt.Services.Web.Tests.dll Source\Tests\JustOrderIt.Web.Public.Tests\bin\Debug\JustOrderIt.Web.Public.Tests.dll" -returntargetcode -hideskipped:All
  # - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - "SET PATH=C:\\Python\\Python-3.4;C:\\Python\\Python-3.4\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "JustOrderIt_coverage.xml"
#  -X gcov
  # - codecov --token=<private repository token>

# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
- Source/packages -> **\Source\packages.config


# -filter:"+[JustOrderIt]* -[JustOrderIt]JustOrderIt.Properties.*"

# -targetargs:"Source\Tests\JustOrderIt.Services.Web.Tests\bin\Debug\JustOrderIt.Web.Tests.dll Source\Tests\JustOrderIt.Web.Administration.Tests\bin\Debug\JustOrderIt.Web.Administration.Tests.dll Source\Tests\JustOrderIt.Web.Public.Tests\bin\Debug\JustOrderIt.Web.Public.Tests.dll Source\Tests\JustOrderIt.Data.DbAccessConfig.Tests\bin\Debug\JustOrderIt.Data.DbAccessConfig.Tests.dll" -returntargetcode -hideskipped:All

